stages:
  - test

Test:
  image: python:3
  stage: test
  script:
    - apt-get update
    - apt-get install ffmpeg libsm6 libxext6 -y
    - pip3 install poetry
    - pip3 install nox==2020.5.24
    - nox
