image: python:3.8
stages:
  - test

Test:
  stage: test
  script:
    - apt-get update
    - apt-get install ffmpeg libsm6 libxext6 -y
    - apt-get install -yq python3-dev
    - pip3 install poetry
    - pip3 install nox==2020.5.24
    - nox
