# Generated by Django 3.2.1 on 2021-05-06 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='original_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='unique_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='original_pictures'),
        ),
    ]
