# Generated by Django 3.2.1 on 2021-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
    ]
