# Workflow name
name: Deploy

# On events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


# Jobs to run
jobs:

  # Job: Deploy to Heroku (https://github.com/marketplace/actions/deploy-to-heroku)
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: checkout repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: export requirements
      - name: Export requirements
        run: |
          pip3 install poetry
          poetry export --format=requirements.txt --output=requirements.txt

      # Step 3: Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
